import markdown
from xhtml2pdf import pisa
import os

def convert_md_to_pdf(source_md, output_pdf):
    # 1. Read Markdown
    with open(source_md, 'r') as f:
        text = f.read()
        
    # 2. Convert to HTML
    html_content = markdown.markdown(text, extensions=['tables'])
    
    # 3. Add Styling
    styled_html = f"""
    <html>
    <head>
    <style>
        body {{
            font-family: Helvetica, sans-serif;
            font-size: 10pt;
            line-height: 1.5;
            color: #333;
        }}
        h1 {{
            color: #1E3A8A;
            font-size: 24pt;
            border-bottom: 2px solid #1E3A8A;
            padding-bottom: 10px;
            margin-top: 30px;
        }}
        h2 {{
            color: #1E3A8A;
            font-size: 18pt;
            margin-top: 20px;
            border-bottom: 1px solid #ccc;
        }}
        h3 {{
            color: #2563EB;
            font-size: 14pt;
            margin-top: 15px;
        }}
        blockquote {{
            background-color: #F3F4F6;
            border-left: 5px solid #1E3A8A;
            padding: 10px;
            margin: 10px 0;
            color: #555;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }}
        th {{
            background-color: #1E3A8A;
            color: white;
        }}
        .footer {{
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8pt;
            color: #999;
        }}
    </style>
    </head>
    <body>
        {html_content}
        <div class="footer">Deep Tech 2026 Proxy Season Report | Generated by Antigravity</div>
    </body>
    </html>
    """
    
    # 4. Write PDF
    with open(output_pdf, "wb") as result_file:
        pisa_status = pisa.CreatePDF(
            styled_html,
            dest=result_file
        )
        
    if pisa_status.err:
        print(f"Error generating PDF: {pisa_status.err}")
    else:
        print(f"PDF successfully created at {output_pdf}")

if __name__ == "__main__":
    source = "dashboard/assets/deep_tech_2026_comprehensive_report.md"
    output = "dashboard/assets/Deep_Tech_2026_Report.pdf"
    
    if not os.path.exists(source):
        print(f"Error: Source file {source} not found.")
    else:
        convert_md_to_pdf(source, output)
